### ISSUE TITLE
Fileset error

### ISSUE THREAD

**Issue by wpoely86** [hpcugent/vsc-administration#35]
```
2016-08-11 11:32:19,428 ERROR      sync_muk_users.__main__ MainThread  Cannot process user vsc10002
Traceback (most recent call last):
  File "/usr/bin/sync_muk_users", line 135, in process
    user.create_scratch_fileset()
  File "/usr/lib/python2.6/site-packages/vsc/administration/user.py", line 437, in create_scratch_fileset
    self.gpfs.make_fileset(path, fileset_name)
  File "/usr/lib/python2.6/site-packages/vsc/filesystem/gpfs.py", line 640, in make_fileset
    " but it already exists.") % (new_fileset_path, fsetpath), GpfsOperationError)
  File "/usr/lib/python2.6/site-packages/vsc/utils/fancylogger.py", line 244, in raiseException
    raise exception, message, tb
GpfsOperationError: makeFileset for new_fileset_path /gpfs/scratch/users/vsc100/vsc10002 returned sane fsetpath /gpfs/scratch/users/vsc100/vsc10002, but it already exists.
ERROR:sync_muk_users.__main__:Cannot process user vsc10002
Traceback (most recent call last):
  File "/usr/bin/sync_muk_users", line 135, in process
    user.create_scratch_fileset()
  File "/usr/lib/python2.6/site-packages/vsc/administration/user.py", line 437, in create_scratch_fileset
    self.gpfs.make_fileset(path, fileset_name)
  File "/usr/lib/python2.6/site-packages/vsc/filesystem/gpfs.py", line 640, in make_fileset
    " but it already exists.") % (new_fileset_path, fsetpath), GpfsOperationError)
  File "/usr/lib/python2.6/site-packages/vsc/utils/fancylogger.py", line 244, in raiseException
    raise exception, message, tb
GpfsOperationError: makeFileset for new_fileset_path /gpfs/scratch/users/vsc100/vsc10002 returned sane fsetpath /gpfs/scratch/users/vsc100/vsc10002, but it already exists.
```

**Comment by wpoely86** [comment]
I have no clue any more what this is about.
